config/routes.rb
Rails.application.routes.draw do
  resources :smstags
  resources :smsreceiveds
  resources :smstags
  resources :smsuserusedtellists
  resources :smsuserusedtellists
  resources :centers
  resources :smsusers
  resources :smslogrecords
  resources :smschongzhirecords
  resources :smsnos
  resources :wxzhuanzhangs
  resources :zf_bduihuas
  resources :zf_bjietus
  resources :l1s
  resources :ls
  resources :welcomes
  devise_for :users, :controllers => {:registrations => "users/registrations"}   
root :to => "ls#index"
  resources :azufangs
  resources :p2pproducts
  resources :documents
  resources :p2pcompanies
  resources :p2pproducts
  resources :yonghus
  resources :blogs
  resources :softnames
  resources :people
  resources :companies
  get 'azufangs/:id/tuiguang' => 'azufangs#tuiguang'

end

app/models/azufang.rb
class Azufang < ActiveRecord::Base
has_attached_file :photo, :styles => { :medium => "300x300>", :thumb => "240x240>" },:default_url => "/images/:style/missing.png",:path => ":rails_root/public/:attachment/:id/:style/:id.:extension",:url => "/:attachment/:id/:style/:id.:extension"  
validates_attachment_content_type :photo, :content_type =>  ["image/jpg", "image/jpeg"]
belongs_to :user 
end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/center.rb
class Center < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/document.rb
class Document < ActiveRecord::Base


def initialize(params = {})
  file = params.delete(:file)
  super
  if file
    self.filename = sanitize_filename(file.original_filename)
    self.content_type = file.content_type
    self.file_contents = file.read
  end
end
private
  def sanitize_filename(filename)
    return File.basename(filename)
  end
NUM_BYTES_IN_MEGABYTE = 1048576
def file_size_under_one_mb
  if (@file.size.to_f / NUM_BYTES_IN_MEGABYTE) > 1
    errors.add(:file, 'File size cannot be over one megabyte.')
  end
end

end

app/models/l.rb
class L < ActiveRecord::Base
end

app/models/l1.rb
class L1 < ActiveRecord::Base
end

app/models/p2pcompany.rb
class P2pcompany < ActiveRecord::Base
end

app/models/p2pproduct.rb
class P2pproduct < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/smsno.rb
class Smsno < ActiveRecord::Base
end

app/models/smstag.rb
class Smstag < ActiveRecord::Base
end

app/models/smstaglist.rb
class Smstaglist < ActiveRecord::Base
end

app/models/smsuser.rb
class Smsuser < ActiveRecord::Base
end

app/models/softname.rb
class Softname < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save :ensure_authentication_token
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthabl
  has_one:azufang
  has_one:smslogrecord
  has_one:smschongzhirecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def ensure_authentication_token
        if authentication_token.blank?
                self.authentication_token = generate_authentication_token
        end
  end
  private
  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end
  end
end

app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

app/models/yonghu.rb
class Yonghu < ActiveRecord::Base
has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/zf_bduihua.rb
class ZfBduihua < ActiveRecord::Base
end

app/models/zf_bjietu.rb
class ZfBjietu < ActiveRecord::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_welcome, only: [:show, :edit, :update, :destroy]

  # GET /welcomes
  # GET /welcomes.json
  def index
    @welcomes = Welcome.all
  end

  # GET /welcomes/1
  # GET /welcomes/1.json
  def show
  end

  # GET /welcomes/new
  def new
    @welcome = Welcome.new
  end

  # GET /welcomes/1/edit
  def edit
  end

  # POST /welcomes
  # POST /welcomes.json
  def create
    @welcome = Welcome.new(welcome_params)

    respond_to do |format|
      if @welcome.save
        format.html { redirect_to @welcome, notice: 'Welcome was successfully created.' }
        format.json { render :show, status: :created, location: @welcome }
      else
        format.html { render :new }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /welcomes/1
  # PATCH/PUT /welcomes/1.json
  def update
    respond_to do |format|
      if @welcome.update(welcome_params)
        format.html { redirect_to @welcome, notice: 'Welcome was successfully updated.' }
        format.json { render :show, status: :ok, location: @welcome }
      else
        format.html { render :edit }
        format.json { render json: @welcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /welcomes/1
  # DELETE /welcomes/1.json
  def destroy
    @welcome.destroy
    respond_to do |format|
      format.html { redirect_to welcomes_url, notice: 'Welcome was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_welcome
      @welcome = Welcome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def welcome_params
      params.require(:welcome).permit(:a)
    end
end

app/helpers/ls_helper.rb
module LsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/welcomes/_form.html.erb
<%= form_for(@welcome) do |f| %>
  <% if @welcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@welcome.errors.count, "error") %> prohibited this welcome from being saved:</h2>

      <ul>
      <% @welcome.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :a %><br>
    <%= f.text_field :a %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/welcomes/edit.html.erb
<h1>Editing Welcome</h1>

<%= render 'form' %>

<%= link_to 'Show', @welcome %> |
<%= link_to 'Back', welcomes_path %>

app/views/welcomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Welcomes</h1>

<table>
  <thead>
    <tr>
      <th>A</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @welcomes.each do |welcome| %>
      <tr>
        <td><%= welcome.a %></td>
        <td><%= link_to 'Show', welcome %></td>
        <td><%= link_to 'Edit', edit_welcome_path(welcome) %></td>
        <td><%= link_to 'Destroy', welcome, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Welcome', new_welcome_path %>

app/views/welcomes/new.html.erb
<h1>New Welcome</h1>

<%= render 'form' %>

<%= link_to 'Back', welcomes_path %>

app/views/welcomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>A:</strong>
  <%= @welcome.a %>
</p>

<%= link_to 'Edit', edit_welcome_path(@welcome) %> |
<%= link_to 'Back', welcomes_path %>